import { useEffect, useState } from "react";
import { CartesianGrid, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from "recharts";
import "./molecular-validation.css";

type Metric = { mean: number; ci95: number[] };
type Row = { method: string; fdr: Metric; power: Metric; power_defined: boolean; paired_power_vs_bonferroni: Metric };
type Scenario = { scenario: string; settings: { calibration_n: number; rho: number; effect: number }; candidate_assumptions: boolean; rows: Row[]; envelope_simultaneous_coverage: Metric; fallback_fraction: Metric };
type Envelope = { current: boolean; scenarios: Scenario[]; run_digest: string; uncertainty: string; effective: { protocol: { repetitions_validation: number; null_draws: number; calibration_failure_budget: number; alpha: number } } };
type Strategy = { strategy: string; nominated: number; measured: number; score_effect: number; exact_permutation_p: number; holm_p_four_strategies: number; direction_concordance: number; bootstrap_percentile_ci95: number[]; sample_scores: { sample_id: string; genotype: string; score: number }[]; leave_one_sample: { omitted_sample: string; effect: number }[] };
type Transport = { current: boolean; nominations_frozen_at: string; freeze_sha256: string; permutation_assignments: number; signed_genes_BY_005: number; signed_gene_family_size: number; strategy_results: Strategy[]; gene_results: { gene: string; direction: number; external_effect: number | null; signed_p: number; BY_q_union_signed_family: number }[]; limits: string[] };
const names: Record<string, string> = { bonferroni_PC_BY: "Bonferroni + PC + BY", fixed_PC_BY: "Prespecified pipeline", oracle_maxT_PC_BY: "Oracle max-T", plugin_maxT_PC_BY: "Estimated-covariance max-T", envelope_maxT_PC_BY: "Confidence-envelope max-T", rank_calibration_PC_BY: "Distribution-free rank calibration", ePCH_eBH: "e-PCH + e-BH", eFilter_bonferroni_split_signs: "Author e-Filter · split signs", single_study_z: "Single-study ranking", multiregion_EB: "Multiregion empirical Bayes", two_study_consensus: "Two-study consensus", multiverse_consensus: "Multiverse consensus" };
const label = (v: string) => names[v] ?? v.replaceAll("_", " ");
const pct = (v: number) => `${(100 * v).toFixed(2)}%`;
const pvalue = (v: number) => v < .001 ? v.toExponential(2) : v.toFixed(4);

function useResult<T>(path: string) {
  const [data, setData] = useState<T>();
  const [error, setError] = useState("");
  useEffect(() => {
    const controller = new AbortController();
    fetch(path, { signal: controller.signal }).then(r => { if (!r.ok) throw new Error(`Artifact unavailable (${r.status})`); return r.json(); }).then(setData).catch(e => { if (e.name !== "AbortError") setError(String(e)); });
    return () => controller.abort();
  }, [path]);
  return { data, error };
}

export function CalibrationUncertainty() {
  const { data, error } = useResult<Envelope>("/api/molecular/envelope");
  const [scenario, setScenario] = useState("n64_rho0.95_z3.5");
  const [effect, setEffect] = useState("3.5");
  if (error) return <p className="mol-warning" role="alert">{error}. No absent result is treated as a passing result.</p>;
  if (!data) return <p aria-live="polite">Loading frozen factorial experiments…</p>;
  const selected = data.scenarios.find(s => s.scenario === scenario) ?? data.scenarios[0];
  const protocol = data.effective.protocol;
  return <>
    {!data.current && <p role="alert" className="mol-warning">These results are stale relative to the frozen source code or protocol.</p>}
    <section className="mol-panel"><span className="mol-eyebrow">FINITE CALIBRATION / ERROR-BUDGET DECOMPOSITION</span><h2>Uncertainty about the uncertainty</h2><p>Correlation is estimated from finite calibration samples. A simultaneous confidence envelope converts that estimation risk into an explicit part of the false-discovery budget.</p><p className="mol-equation">FDR ≤ (α − δ) P(good calibration) + P(bad calibration) ≤ α</p><div className="mol-mini-stats"><div><b>{data.scenarios.length}</b><span>prespecified scenarios</span></div><div><b>{protocol.repetitions_validation.toLocaleString()}</b><span>repetitions per scenario</span></div><div><b>{protocol.null_draws.toLocaleString()}</b><span>fresh null draws per bank</span></div><div><b>{pct(protocol.calibration_failure_budget)}</b><span>global calibration budget</span></div></div><p className="mol-note">Independent Gaussian calibration rows, known unit marginal variances, matched covariance and comparable fixed pipeline nulls are required. The component methods are established; publication novelty is not certified.</p></section>
    <section className="mol-panel"><div className="mol-panel-head"><h2>Where does calibration help?</h2><label>Signal strength<select aria-label="Heatmap signal strength" value={effect} onChange={e => setEffect(e.target.value)}>{["2.5", "3.5", "4.5"].map(v => <option key={v}>{v}</option>)}</select></label></div><p className="mol-note">Power difference, confidence-envelope minus Bonferroni. Blue: gain. Ochre: loss. Click a cell for the complete comparison; differences are descriptive, not simultaneous significance tests.</p><div className="mol-scroll"><table className="mol-heatmap"><thead><tr><th>Calibration samples</th>{[.1, .8, .95].map(rho => <th key={rho}>Pipeline ρ = {rho}</th>)}</tr></thead><tbody>{[16, 64, 256].map(n => <tr key={n}><th>n = {n}</th>{[.1, .8, .95].map(rho => { const name = `n${n}_rho${rho}_z${effect}`; const entry = data.scenarios.find(s => s.scenario === name); const delta = entry?.rows.find(r => r.method === "envelope_maxT_PC_BY")?.paired_power_vs_bonferroni.mean ?? 0; return <td key={rho}><button aria-label={`${name}: power difference ${pct(delta)}`} onClick={() => setScenario(name)} style={{ background: delta >= 0 ? `rgba(35,91,117,${.06 + Math.min(.5, delta * 4)})` : `rgba(165,116,64,${.06 + Math.min(.5, -delta * 4)})` }}>{delta > 0 ? "+" : ""}{(delta * 100).toFixed(2)} pp</button></td>; })}</tr>)}</tbody></table></div></section>
    <section className="mol-panel"><label className="mol-feature">Full scenario comparison<select aria-label="Finite calibration scenario" value={selected.scenario} onChange={e => setScenario(e.target.value)}>{data.scenarios.map(s => <option key={s.scenario} value={s.scenario}>{label(s.scenario)}</option>)}</select></label>{!selected.candidate_assumptions && <p className="mol-warning">Assumption-violation stress test. The theoretical guarantee does not apply, even if observed FDR is small.</p>}<div className="mol-mini-stats"><div><b>{pct(selected.envelope_simultaneous_coverage.mean)}</b><span>simultaneous envelope coverage</span></div><div><b>{pct(selected.fallback_fraction.mean)}</b><span>Bonferroni fallback fraction</span></div></div><div className="mol-scroll"><table><thead><tr><th>Method</th><th>Mean FDP · 95% interval</th><th>Power</th><th>Δ power vs Bonferroni</th></tr></thead><tbody>{selected.rows.map(r => <tr key={r.method} className={r.method === "envelope_maxT_PC_BY" ? "selected" : ""}><td>{label(r.method)}</td><td>{pct(r.fdr.mean)}<small>{r.fdr.ci95.map(pct).join(" – ")}</small></td><td>{r.power_defined ? pct(r.power.mean) : "No alternatives"}</td><td>{r.power_defined ? `${(r.paired_power_vs_bonferroni.mean * 100).toFixed(2)} pp` : "—"}</td></tr>)}</tbody></table></div><p className="mol-note">{data.uncertainty} e-Filter is an empirical comparator: its additional distribution/calibrator conditions are not certified in these simulations. Exact author-function parity was checked independently in R.</p><code className="mol-digest">{data.run_digest}</code></section>
  </>;
}

export function ExternalTransport() {
  const { data, error } = useResult<Transport>("/api/molecular/transport");
  const [strategy, setStrategy] = useState("multiverse_consensus");
  const [search, setSearch] = useState("");
  if (error) return <p className="mol-warning" role="alert">{error}. The cohort is not reported as validated without a completed result.</p>;
  if (!data) return <p aria-live="polite">Checking external-cohort provenance…</p>;
  const selected = data.strategy_results.find(r => r.strategy === strategy) ?? data.strategy_results[0];
  const genes = data.gene_results.filter(g => g.gene.toLowerCase().includes(search.toLowerCase()));
  return <>
    {!data.current && <p className="mol-warning" role="alert">External results no longer match the frozen code, nominations or inputs.</p>}
    <section className="mol-panel"><span className="mol-eyebrow">FROZEN PUBLIC-COHORT TRANSPORT / GSE261670</span><h2>From nomination to an untouched cohort</h2><div className="mol-provenance-flow"><div><b>Development</b><span>GSE107958 + GSE145613</span><small>Previously explored mouse cerebellum</small></div><div><b>Frozen nominations</b><span>Four strategies · 50 genes each</span><small>{new Date(data.nominations_frozen_at).toLocaleString()}</small></div><div><b>External evaluation</b><span>6 WT + 6 Q84 · 65 weeks</span><small>Untreated cerebellum, separate publication</small></div></div><p className="mol-note">One tissue and age stratum only. Treatment arms are excluded. This tests cross-model/age transport, not a new therapeutic mechanism, patient prediction or the CE-maxT Gaussian assumptions.</p><div className="mol-mini-stats"><div><b>{data.permutation_assignments}</b><span>all balanced label assignments</span></div><div><b>{data.signed_gene_family_size}</b><span>unique frozen signed hypotheses</span></div><div><b>{data.signed_genes_BY_005}</b><span>signed genes at BY q ≤ .05</span></div></div></section>
    <section className="mol-panel"><h2>All four strategies, including the simple baseline</h2><div className="mol-scroll"><table><thead><tr><th>Frozen strategy</th><th>Sign agreement</th><th>Aggregate p</th><th>Holm-adjusted p</th><th>Measured</th></tr></thead><tbody>{data.strategy_results.map(r => <tr key={r.strategy} className={r.strategy === strategy ? "selected" : ""}><td><button className="mol-link" onClick={() => setStrategy(r.strategy)}>{label(r.strategy)}</button></td><td>{pct(r.direction_concordance)}</td><td>{pvalue(r.exact_permutation_p)}</td><td>{pvalue(r.holm_p_four_strategies)}</td><td>{r.measured}/{r.nominated}</td></tr>)}</tbody></table></div><p className="mol-note">Sign agreement is descriptive; genes are correlated and are not binomial trials. Aggregate tests permute whole samples. A significant signature does not imply every nominated gene replicates, nor that one strategy is significantly better than another.</p></section>
    <div className="mol-columns"><section className="mol-panel"><h2>{label(selected.strategy)}</h2><div className="mol-chart"><ResponsiveContainer><ScatterChart margin={{ left: 8, right: 25, top: 15, bottom: 15 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="group" type="number" domain={[-.45, 1.45]} ticks={[0, 1]} tickFormatter={x => x === 0 ? "WT" : "Q84"} /><YAxis dataKey="score" name="Frozen signature score" /><ReferenceLine y={0} stroke="#9cabb3" /><Tooltip content={({ payload }) => { const v = payload?.[0]?.payload; return v ? <div className="mol-tooltip"><b>{v.sample_id}</b><p>{v.genotype} · {v.score.toFixed(3)}</p></div> : null; }} />{["WT", "Q84"].map((genotype, group) => <Scatter key={genotype} fill={group === 0 ? "#879695" : "#235b75"} data={selected.sample_scores.filter(s => s.genotype === genotype).map((s, i) => ({ ...s, group: group + (i - 2.5) * .035 }))} />)}</ScatterChart></ResponsiveContainer></div><p className="mol-note">Each point is one public sample; horizontal jitter is display-only. Standardization uses no genotype labels. Positive score indicates the direction nominated from development.</p></section><section className="mol-panel"><h2>Sample-level uncertainty</h2><p className="mol-line"><span>Mean score contrast</span><b>{selected.score_effect.toFixed(3)}</b></p><p className="mol-line"><span>Stratified bootstrap 95% interval</span><b>{selected.bootstrap_percentile_ci95.map(x => x.toFixed(3)).join(" – ")}</b></p><h3>Leave-one-sample effect range</h3><p className="mol-equation">{Math.min(...selected.leave_one_sample.map(x => x.effect)).toFixed(3)} — {Math.max(...selected.leave_one_sample.map(x => x.effect)).toFixed(3)}</p><p className="mol-note">Bootstrap intervals are descriptive with n = 6 per group. Missing sex/litter annotations limit confounder assessment. The complete influence table remains in the reproducible result artifact.</p></section></div>
    <section className="mol-panel"><div className="mol-panel-head"><h2>Signed gene evidence</h2><input aria-label="Search nominated gene" placeholder="Search gene symbol" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="mol-scroll mol-gene-table"><table><thead><tr><th>Gene</th><th>Frozen direction</th><th>Held-out log2 contrast</th><th>Exact p</th><th>BY q · union family</th></tr></thead><tbody>{genes.map(g => <tr key={`${g.gene}-${g.direction}`}><td>{g.gene}</td><td>{g.direction > 0 ? "Increase" : "Decrease"}</td><td>{g.external_effect === null ? "Missing" : g.external_effect.toFixed(3)}</td><td>{pvalue(g.signed_p)}</td><td>{pvalue(g.BY_q_union_signed_family)}</td></tr>)}</tbody></table></div><p className="mol-note">Missing nominations remain in the testing family at p = 1; no replacement genes are selected after seeing the cohort.</p></section>
    <section className="mol-panel"><h2>Scope of the evidence</h2><ul className="mol-issues">{data.limits.map(limit => <li key={limit}>{limit}</li>)}</ul><code className="mol-digest">Frozen nomination digest · {data.freeze_sha256}</code></section>
  </>;
}

export function AnimalBlockedValidation() {
  const { data, error } = useResult<{ current: boolean; all_fits_converged: boolean; folds: unknown[]; summaries: { method: string; mean_fold_mse: number; paired_mean_difference_vs_unshrunk: number; folds_better_than_unshrunk: number }[] }>("/api/molecular/animal-blocks");
  if (error) return <p className="mol-warning">Animal-blocked artifact unavailable: {error}</p>;
  if (!data) return <p aria-live="polite">Loading animal-blocked validation…</p>;
  return <section className="mol-panel"><span className="mol-eyebrow">INTERNAL EVALUATION / ALL REPEATED REGIONS HELD OUT TOGETHER</span><h2>What survives holding out entire animals?</h2>{!data.current && <p className="mol-warning" role="alert">Animal-blocked results are stale.</p>}<p>{data.folds.length} leave-one-case/one-control pairs. Every brain region from both held animals is excluded before learning the covariance dictionary and mixture weights.</p><div className="mol-scroll"><table><thead><tr><th>Model</th><th>Held-out contrast MSE</th><th>Δ MSE vs unshrunk</th><th>Pairs with lower MSE</th></tr></thead><tbody>{data.summaries.map(row => <tr key={row.method}><td>{label(row.method)}</td><td>{row.mean_fold_mse.toFixed(5)}</td><td>{row.paired_mean_difference_vs_unshrunk.toFixed(5)}</td><td>{row.folds_better_than_unshrunk}/{data.folds.length}</td></tr>)}</tbody></table></div><p className="mol-note">All mixture fits converged: {data.all_fits_converged ? "yes" : "NO"}. These overlapping folds are not independent experiments. No iid-fold significance test is reported. The target is a noisy expression contrast, not a patient's prognosis; upstream source filtering and expression-unit limitations remain.</p></section>;
}
